[package]
name = "robot_simulator_rust"
version = "0.1.0"
authors = ["Nobuyuki Matsui <nobuyuki.matsui@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
